spring:
    application:
        name: spring-boot-oauth2-server
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
    main:
        banner-mode: 'off'
security:
    oauth2:
        resource:
            filter-order: 3
        client:
            authenticationScheme: header
logging:
    level:
    # org.springframework.security: DEBUG

server:
    port: 8085
    error:
        whitelabel:
            enabled: false