version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.15.0
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - run
      - --server
      - --log-level=debug
   #api_server:
   #image: openpolicyagent/demo-restful-api:0.2
   #ports:
   #- 5000:5000
   #environment:
   #- OPA_ADDR=http://opa:8181
   #- POLICY_PATH=/v1/data/httpapi/authz 
